Update index.d.ts
Add's missing return types to fix TS7010 errors

```
node_modules/nengi/index.d.ts(10,5): error TS7010: 'forEach', which lacks return-type annotation, implicitly has an 'any' return type.
[1] node_modules/nengi/index.d.ts(45,9): error TS7010: 'on', which lacks return-type annotation, implicitly has an 'any' return type.
[1] node_modules/nengi/index.d.ts(166,9): error TS7010: 'on', which lacks return-type annotation, implicitly has an 'any' return type.
```